apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: empms-attendance
  name: empms-attendance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-attendance
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empms-attendance
    spec:
      containers:
      - image: registry.digitalocean.com/empmsfa/empms-attendance:latest
        imagePullPolicy: Always
        name: empms-attendance
        ports:
        - containerPort: 8081
        resources: {}
        env:
          - name: DEPLOY_TIME
            value: 18:35
---
