apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: empms-employee
  name: empms-employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-employee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empms-employee
    spec:
      containers:
      - image: opstree/empms-employee:1.0
        imagePullPolicy: Always
        name: empms-employee
        ports:
        - containerPort: 8083
        resources: {}
        env:
          - name: DEPLOY_TIME
            value: 19:40 
