apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: empms-frontend
  name: empms-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empms-frontend
    spec:
      containers:
      - image: opstree/empms-frontend:1.0
        imagePullPolicy: Always
        name: empms-frontend
        ports:
        - containerPort: 5000
        resources: {}
        env:
          - name: DEPLOY_TIME
            value: 22:10
